Revert "sqlite: Upgrade to SQLite 3.19.3"
This causes Yahoo Finance to fail on opening with:
java.lang.IllegalArgumentException: column '_id' does not exist
    at
android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
    at
android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)

Bug: 62431773
Test: App stops crashing
This reverts commit 1ea291d14f0cf30fd85f00307dbcb9991912ed2c.